// omacos native helper — the two things macOS can do well but exposes no CLI for.
//
// Built on demand by `omacos-cmd-build-helper` into ~/.local/state/omacos/bin,
// because the Xcode Command Line Tools are a hard install requirement anyway
// and a compiled 40KB binary beats shipping a second OCR engine from Homebrew.
//
//   omacos-helper ocr <image>   text in the image, one line per recognised line
//   omacos-helper color         the system eyedropper, printed as #RRGGBB
//   omacos-helper clipboard     watch the pasteboard, printing each new text
//                               entry NUL-terminated
//   omacos-helper fonts         font families you could set, one per line
//   omacos-helper qr <text>     a QR code drawn in the terminal
//   omacos-helper menubar      is the macOS menu bar actually on screen
//   omacos-helper copy-file <path>
//                               put a file on the clipboard as a file, so
//                               pasting into Mail or Finder attaches it
//   omacos-helper qr-decode <image>
//                               read a QR code; the value goes to the
//                               clipboard, marked concealed, and is never
//                               printed — only what kind of thing it was

import AppKit
import CoreImage
import CoreText
import Vision

func die(_ message: String) -> Never {
    FileHandle.standardError.write(Data("omacos-helper: \(message)\n".utf8))
    exit(1)
}

// Vision, not tesseract: it ships with the OS, handles rotation and low
// contrast better, and needs no language data files on disk.
func ocr(path: String) {
    guard let image = NSImage(contentsOfFile: path),
          let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil)
    else { die("cannot read image: \(path)") }

    let request = VNRecognizeTextRequest()
    request.recognitionLevel = .accurate
    request.usesLanguageCorrection = true

    do {
        try VNImageRequestHandler(cgImage: cgImage, options: [:]).perform([request])
    } catch {
        die("OCR failed: \(error.localizedDescription)")
    }

    let lines = (request.results ?? []).compactMap { $0.topCandidates(1).first?.string }
    // Reading order, not detection order: Vision returns observations roughly
    // top-to-bottom already, but joining without a newline would run an address
    // block into one line.
    print(lines.joined(separator: "\n"))
}

// NSColorSampler is the same magnifier the system colour picker uses, so the
// pixel under the loupe is the pixel you get.
func pickColor() {
    let app = NSApplication.shared
    // .accessory keeps this out of the Dock and the app switcher: it is a
    // loupe that lives for two seconds, not an application.
    app.setActivationPolicy(.accessory)
    NSColorSampler().show { color in
        guard let picked = color?.usingColorSpace(.sRGB) else { exit(1) }
        let channel = { (value: CGFloat) in Int((value * 255).rounded()) }
        print(String(format: "#%02X%02X%02X",
                     channel(picked.redComponent),
                     channel(picked.greenComponent),
                     channel(picked.blueComponent)))
        exit(0)
    }
    app.run()
}

// Polling is how you watch NSPasteboard — it posts no change notification.
// Doing it inside one long-lived process keeps the cost to a changeCount read
// twice a second, rather than a shell and an osascript on every tick.
func watchClipboard() {
    let pasteboard = NSPasteboard.general
    var lastChange = pasteboard.changeCount

    // The conventions password managers and clipboard tools agreed on so that
    // history tools skip their entries. Honouring them is the difference
    // between a clipboard history and a password log.
    let doNotRecord: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    while true {
        if pasteboard.changeCount != lastChange {
            lastChange = pasteboard.changeCount
            let types = Set((pasteboard.types ?? []).map { $0.rawValue })
            if types.isDisjoint(with: doNotRecord),
               let text = pasteboard.string(forType: .string),
               !text.isEmpty {
                // NUL-terminated: the one byte that cannot appear in the text.
                FileHandle.standardOutput.write(Data(text.utf8) + Data([0]))
            }
        }
        Thread.sleep(forTimeInterval: 0.4)
    }
}

// The font families you could actually set the terminal to.
//
// Three tools claim to answer this and all three are wrong here. atsutil and
// system_profiler report only fonts registered with the system font database,
// and `ghostty +list-fonts` the same — none of them see a Nerd Font that
// Homebrew dropped into ~/Library/Fonts, which is every font omacos would ever
// be asked to set. So the files are read directly, which is the ground truth.
//
// Deliberately not filtered to the monospace trait: on this machine that trait
// is set on "JetBrainsMono Nerd Font Mono" but not on "JetBrainsMono Nerd
// Font", which is the family actually in use. A filter that hides the font you
// are already using is worse than a list with a few extra rows in it.
func fontFamilies() {
    var families = Set<String>()

    // Registered, and fixed-pitch: the system's own terminal-shaped fonts.
    for name in (CTFontManagerCopyAvailableFontFamilyNames() as? [String] ?? []) {
        if let font = NSFont(name: name, size: 12), font.isFixedPitch {
            families.insert(name)
        }
    }

    // Installed by hand or by Homebrew. Anything here was put there on purpose.
    let manager = FileManager.default
    for directory in ["\(NSHomeDirectory())/Library/Fonts", "/Library/Fonts"] {
        guard let entries = try? manager.contentsOfDirectory(atPath: directory) else { continue }
        for entry in entries
        where ["ttf", "otf", "ttc", "dfont"].contains((entry as NSString).pathExtension.lowercased()) {
            let url = URL(fileURLWithPath: directory).appendingPathComponent(entry)
            guard let descriptors =
                CTFontManagerCreateFontDescriptorsFromURL(url as CFURL) as? [CTFontDescriptor]
            else { continue }
            for descriptor in descriptors {
                if let family = CTFontDescriptorCopyAttribute(descriptor, kCTFontFamilyNameAttribute) as? String {
                    families.insert(family)
                }
            }
        }
    }

    for family in families.sorted(by: { $0.localizedCaseInsensitiveCompare($1) == .orderedAscending }) {
        print(family)
    }
}

// A QR code you can point a phone at, drawn where you already are.
//
// Two rows of modules per line of text, as half blocks, so the code stays
// square in a terminal whose cells are twice as tall as they are wide.
func qrCode(_ text: String) {
    guard let filter = CIFilter(name: "CIQRCodeGenerator") else { die("no QR generator") }
    filter.setValue(Data(text.utf8), forKey: "inputMessage")
    // M corrects ~15%, which is plenty for a screen and keeps the code small
    // enough to fit a terminal window.
    filter.setValue("M", forKey: "inputCorrectionLevel")
    guard let image = filter.outputImage else { die("could not encode") }
    let bitmap = NSBitmapImageRep(ciImage: image)
    let width = bitmap.pixelsWide, height = bitmap.pixelsHigh

    // Every line is printed black-on-white explicitly. Left to the terminal's
    // own colours, a dark theme renders the code inverted — which most phone
    // scanners will not read.
    let start = "\u{1B}[30;47m", end = "\u{1B}[0m"
    // The quiet zone is part of the spec, not decoration: without four modules
    // of margin a scanner cannot find the code's edges.
    let margin = 4
    let blank = String(repeating: " ", count: width + margin * 2)

    func dark(_ x: Int, _ y: Int) -> Bool {
        guard x >= 0, y >= 0, x < width, y < height else { return false }
        return (bitmap.colorAt(x: x, y: y)?.brightnessComponent ?? 1) < 0.5
    }

    print("")
    for _ in 0..<(margin / 2) { print(start + blank + end) }
    var y = 0
    while y < height {
        var line = String(repeating: " ", count: margin)
        for x in 0..<width {
            switch (dark(x, y), dark(x, y + 1)) {
            case (true, true):   line += "\u{2588}"
            case (true, false):  line += "\u{2580}"
            case (false, true):  line += "\u{2584}"
            case (false, false): line += " "
            }
        }
        line += String(repeating: " ", count: margin)
        print(start + line + end)
        y += 2
    }
    for _ in 0..<(margin / 2) { print(start + blank + end) }
    print("")
}

// Read a QR code and put it on the clipboard without ever showing it.
//
// A QR code routinely carries a secret: the otpauth:// URI behind a 2FA setup
// code is the obvious one. So the value is written straight to the pasteboard
// and this prints only what kind of thing it was. Nothing to scroll back to,
// nothing in a notification, nothing in a shell history.
//
// It is marked ConcealedType, which is the convention every clipboard manager
// honours — omacos's own watcher skips it, which is what keeps a 2FA seed out
// of the history it would otherwise sit in forever.
func decodeQR(path: String) {
    guard let image = NSImage(contentsOfFile: path),
          let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil)
    else { die("cannot read image: \(path)") }

    let request = VNDetectBarcodesRequest()
    // QR only. Dense screen content false-positives as a 1D barcode readily,
    // and a wrong answer here is worse than no answer.
    request.symbologies = [.qr]

    do {
        try VNImageRequestHandler(cgImage: cgImage, options: [:]).perform([request])
    } catch {
        die("decode failed: \(error.localizedDescription)")
    }

    let values = (request.results ?? []).compactMap { $0.payloadStringValue }
    guard let value = values.first, !value.isEmpty else {
        FileHandle.standardError.write(Data("omacos-helper: no QR code in that selection\n".utf8))
        exit(2)
    }

    let pasteboard = NSPasteboard.general
    pasteboard.declareTypes(
        [.string, NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")],
        owner: nil)
    pasteboard.setString(value, forType: .string)

    // What it was, never what it said.
    let kind: String
    switch true {
    case value.hasPrefix("otpauth:"):        kind = "a one-time-password setup code"
    case value.hasPrefix("WIFI:"):           kind = "Wi-Fi credentials"
    case value.hasPrefix("mailto:"):         kind = "an email address"
    case value.hasPrefix("tel:"):            kind = "a phone number"
    case value.hasPrefix("BEGIN:VCARD"):     kind = "a contact card"
    case value.hasPrefix("http://"),
         value.hasPrefix("https://"):        kind = "a link"
    default:                                 kind = "\(value.count) characters of text"
    }
    print(kind)
    if values.count > 1 {
        FileHandle.standardError.write(
            Data("omacos-helper: \(values.count) codes in that selection; took the first\n".utf8))
    }
}

// Put a file on the pasteboard as a *file*, not as its path.
//
// Omarchy copies a file:// URI, which is what a Linux app that takes file
// drops expects. On macOS the equivalent is the file's URL on the pasteboard:
// paste into Mail and it attaches, into Finder and it copies, into a text
// field and you still get the path. Writing the path as text does none of that.
func copyFile(path: String) {
    let url = URL(fileURLWithPath: path)
    guard FileManager.default.fileExists(atPath: url.path) else { die("no such file: \(path)") }
    // One item carrying both: the file URL, which is what Mail and Finder read,
    // and the path as plain text, so pasting into a text field is not silence.
    let item = NSPasteboardItem()
    item.setString(url.absoluteString, forType: .fileURL)
    item.setString(url.path, forType: .string)
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    guard pasteboard.writeObjects([item]) else { die("could not write the pasteboard") }
    print(url.path)
}

// Whether the macOS menu bar is actually on screen, rather than whether a
// preference asking for it to be hidden has been written.
//
// The two are not the same thing and that is the whole point: _HIHideMenuBar
// is read by the window server when the session starts, so writing it reports
// success while the bar stays exactly where it was until you log out. A status
// that reads the preference agrees with itself and disagrees with the screen.
//
// The menu bar is a layer-24 window at the top of a display, about 30pt tall.
// Nothing else looks like that. Reading window geometry needs no screen
// recording permission — only window *titles* do.
func menuBarVisible() {
    let windows = CGWindowListCopyWindowInfo([.optionOnScreenOnly], kCGNullWindowID)
        as? [[String: Any]] ?? []
    var bars: [String] = []
    for window in windows {
        guard (window[kCGWindowLayer as String] as? Int) == 24,
              let bounds = window[kCGWindowBounds as String] as? [String: CGFloat],
              let height = bounds["Height"], let width = bounds["Width"], let y = bounds["Y"],
              height >= 20, height <= 60, width > 400, y <= 1
        else { continue }
        bars.append(String(format: "%.0fx%.0f", width, height))
    }
    if bars.isEmpty {
        print("hidden")
    } else {
        print("visible \(bars.joined(separator: " "))")
    }
}

switch CommandLine.arguments.dropFirst().first {
case "ocr":
    guard CommandLine.arguments.count > 2 else { die("usage: omacos-helper ocr <image>") }
    ocr(path: CommandLine.arguments[2])
case "color":
    pickColor()
case "menubar":
    menuBarVisible()
case "copy-file":
    guard let path = CommandLine.arguments.dropFirst(2).first else {
        die("usage: omacos-helper copy-file <path>")
    }
    copyFile(path: path)
case "qr-decode":
    guard let path = CommandLine.arguments.dropFirst(2).first else {
        die("usage: omacos-helper qr-decode <image>")
    }
    decodeQR(path: path)
case "qr":
    guard let text = CommandLine.arguments.dropFirst(2).first, !text.isEmpty else {
        die("usage: omacos-helper qr <text>")
    }
    qrCode(text)
case "fonts":
    fontFamilies()
case "clipboard":
    watchClipboard()
default:
    // Every subcommand, not the two it launched with. A usage line that stops
    // being updated is how you end up believing a working binary is stale.
    die("usage: omacos-helper <ocr <image>|color|clipboard|fonts|menubar|qr <text>|qr-decode <image>|copy-file <path>>")
}
