// omacos native helper — the two things macOS can do well but exposes no CLI for.
//
// Built on demand by `omacos-cmd-build-helper` into ~/.local/state/omacos/bin,
// because the Xcode Command Line Tools are a hard install requirement anyway
// and a compiled 40KB binary beats shipping a second OCR engine from Homebrew.
//
//   omacos-helper ocr <image>   text in the image, one line per recognised line
//   omacos-helper color         the system eyedropper, printed as #RRGGBB
//   omacos-helper clipboard     watch the pasteboard, printing each new text
//                               entry NUL-terminated

import AppKit
import Vision

func die(_ message: String) -> Never {
    FileHandle.standardError.write(Data("omacos-helper: \(message)\n".utf8))
    exit(1)
}

// Vision, not tesseract: it ships with the OS, handles rotation and low
// contrast better, and needs no language data files on disk.
func ocr(path: String) {
    guard let image = NSImage(contentsOfFile: path),
          let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil)
    else { die("cannot read image: \(path)") }

    let request = VNRecognizeTextRequest()
    request.recognitionLevel = .accurate
    request.usesLanguageCorrection = true

    do {
        try VNImageRequestHandler(cgImage: cgImage, options: [:]).perform([request])
    } catch {
        die("OCR failed: \(error.localizedDescription)")
    }

    let lines = (request.results ?? []).compactMap { $0.topCandidates(1).first?.string }
    // Reading order, not detection order: Vision returns observations roughly
    // top-to-bottom already, but joining without a newline would run an address
    // block into one line.
    print(lines.joined(separator: "\n"))
}

// NSColorSampler is the same magnifier the system colour picker uses, so the
// pixel under the loupe is the pixel you get.
func pickColor() {
    let app = NSApplication.shared
    // .accessory keeps this out of the Dock and the app switcher: it is a
    // loupe that lives for two seconds, not an application.
    app.setActivationPolicy(.accessory)
    NSColorSampler().show { color in
        guard let picked = color?.usingColorSpace(.sRGB) else { exit(1) }
        let channel = { (value: CGFloat) in Int((value * 255).rounded()) }
        print(String(format: "#%02X%02X%02X",
                     channel(picked.redComponent),
                     channel(picked.greenComponent),
                     channel(picked.blueComponent)))
        exit(0)
    }
    app.run()
}

// Polling is how you watch NSPasteboard — it posts no change notification.
// Doing it inside one long-lived process keeps the cost to a changeCount read
// twice a second, rather than a shell and an osascript on every tick.
func watchClipboard() {
    let pasteboard = NSPasteboard.general
    var lastChange = pasteboard.changeCount

    // The conventions password managers and clipboard tools agreed on so that
    // history tools skip their entries. Honouring them is the difference
    // between a clipboard history and a password log.
    let doNotRecord: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    while true {
        if pasteboard.changeCount != lastChange {
            lastChange = pasteboard.changeCount
            let types = Set((pasteboard.types ?? []).map { $0.rawValue })
            if types.isDisjoint(with: doNotRecord),
               let text = pasteboard.string(forType: .string),
               !text.isEmpty {
                // NUL-terminated: the one byte that cannot appear in the text.
                FileHandle.standardOutput.write(Data(text.utf8) + Data([0]))
            }
        }
        Thread.sleep(forTimeInterval: 0.4)
    }
}

switch CommandLine.arguments.dropFirst().first {
case "ocr":
    guard CommandLine.arguments.count > 2 else { die("usage: omacos-helper ocr <image>") }
    ocr(path: CommandLine.arguments[2])
case "color":
    pickColor()
case "clipboard":
    watchClipboard()
default:
    die("usage: omacos-helper <ocr <image>|color>")
}
