// omacos native helper — the two things macOS can do well but exposes no CLI for.
//
// Built on demand by `omacos-cmd-build-helper` into ~/.local/state/omacos/bin,
// because the Xcode Command Line Tools are a hard install requirement anyway
// and a compiled 40KB binary beats shipping a second OCR engine from Homebrew.
//
//   omacos-helper ocr <image>   text in the image, one line per recognised line
//   omacos-helper color         the system eyedropper, printed as #RRGGBB
//   omacos-helper clipboard     watch the pasteboard, printing each new text
//                               entry NUL-terminated
//   omacos-helper fonts         font families you could set, one per line
//   omacos-helper qr <text>     a QR code drawn in the terminal

import AppKit
import CoreImage
import CoreText
import Vision

func die(_ message: String) -> Never {
    FileHandle.standardError.write(Data("omacos-helper: \(message)\n".utf8))
    exit(1)
}

// Vision, not tesseract: it ships with the OS, handles rotation and low
// contrast better, and needs no language data files on disk.
func ocr(path: String) {
    guard let image = NSImage(contentsOfFile: path),
          let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil)
    else { die("cannot read image: \(path)") }

    let request = VNRecognizeTextRequest()
    request.recognitionLevel = .accurate
    request.usesLanguageCorrection = true

    do {
        try VNImageRequestHandler(cgImage: cgImage, options: [:]).perform([request])
    } catch {
        die("OCR failed: \(error.localizedDescription)")
    }

    let lines = (request.results ?? []).compactMap { $0.topCandidates(1).first?.string }
    // Reading order, not detection order: Vision returns observations roughly
    // top-to-bottom already, but joining without a newline would run an address
    // block into one line.
    print(lines.joined(separator: "\n"))
}

// NSColorSampler is the same magnifier the system colour picker uses, so the
// pixel under the loupe is the pixel you get.
func pickColor() {
    let app = NSApplication.shared
    // .accessory keeps this out of the Dock and the app switcher: it is a
    // loupe that lives for two seconds, not an application.
    app.setActivationPolicy(.accessory)
    NSColorSampler().show { color in
        guard let picked = color?.usingColorSpace(.sRGB) else { exit(1) }
        let channel = { (value: CGFloat) in Int((value * 255).rounded()) }
        print(String(format: "#%02X%02X%02X",
                     channel(picked.redComponent),
                     channel(picked.greenComponent),
                     channel(picked.blueComponent)))
        exit(0)
    }
    app.run()
}

// Polling is how you watch NSPasteboard — it posts no change notification.
// Doing it inside one long-lived process keeps the cost to a changeCount read
// twice a second, rather than a shell and an osascript on every tick.
func watchClipboard() {
    let pasteboard = NSPasteboard.general
    var lastChange = pasteboard.changeCount

    // The conventions password managers and clipboard tools agreed on so that
    // history tools skip their entries. Honouring them is the difference
    // between a clipboard history and a password log.
    let doNotRecord: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    while true {
        if pasteboard.changeCount != lastChange {
            lastChange = pasteboard.changeCount
            let types = Set((pasteboard.types ?? []).map { $0.rawValue })
            if types.isDisjoint(with: doNotRecord),
               let text = pasteboard.string(forType: .string),
               !text.isEmpty {
                // NUL-terminated: the one byte that cannot appear in the text.
                FileHandle.standardOutput.write(Data(text.utf8) + Data([0]))
            }
        }
        Thread.sleep(forTimeInterval: 0.4)
    }
}

// The font families you could actually set the terminal to.
//
// Three tools claim to answer this and all three are wrong here. atsutil and
// system_profiler report only fonts registered with the system font database,
// and `ghostty +list-fonts` the same — none of them see a Nerd Font that
// Homebrew dropped into ~/Library/Fonts, which is every font omacos would ever
// be asked to set. So the files are read directly, which is the ground truth.
//
// Deliberately not filtered to the monospace trait: on this machine that trait
// is set on "JetBrainsMono Nerd Font Mono" but not on "JetBrainsMono Nerd
// Font", which is the family actually in use. A filter that hides the font you
// are already using is worse than a list with a few extra rows in it.
func fontFamilies() {
    var families = Set<String>()

    // Registered, and fixed-pitch: the system's own terminal-shaped fonts.
    for name in (CTFontManagerCopyAvailableFontFamilyNames() as? [String] ?? []) {
        if let font = NSFont(name: name, size: 12), font.isFixedPitch {
            families.insert(name)
        }
    }

    // Installed by hand or by Homebrew. Anything here was put there on purpose.
    let manager = FileManager.default
    for directory in ["\(NSHomeDirectory())/Library/Fonts", "/Library/Fonts"] {
        guard let entries = try? manager.contentsOfDirectory(atPath: directory) else { continue }
        for entry in entries
        where ["ttf", "otf", "ttc", "dfont"].contains((entry as NSString).pathExtension.lowercased()) {
            let url = URL(fileURLWithPath: directory).appendingPathComponent(entry)
            guard let descriptors =
                CTFontManagerCreateFontDescriptorsFromURL(url as CFURL) as? [CTFontDescriptor]
            else { continue }
            for descriptor in descriptors {
                if let family = CTFontDescriptorCopyAttribute(descriptor, kCTFontFamilyNameAttribute) as? String {
                    families.insert(family)
                }
            }
        }
    }

    for family in families.sorted(by: { $0.localizedCaseInsensitiveCompare($1) == .orderedAscending }) {
        print(family)
    }
}

// A QR code you can point a phone at, drawn where you already are.
//
// Two rows of modules per line of text, as half blocks, so the code stays
// square in a terminal whose cells are twice as tall as they are wide.
func qrCode(_ text: String) {
    guard let filter = CIFilter(name: "CIQRCodeGenerator") else { die("no QR generator") }
    filter.setValue(Data(text.utf8), forKey: "inputMessage")
    // M corrects ~15%, which is plenty for a screen and keeps the code small
    // enough to fit a terminal window.
    filter.setValue("M", forKey: "inputCorrectionLevel")
    guard let image = filter.outputImage else { die("could not encode") }
    let bitmap = NSBitmapImageRep(ciImage: image)
    let width = bitmap.pixelsWide, height = bitmap.pixelsHigh

    // Every line is printed black-on-white explicitly. Left to the terminal's
    // own colours, a dark theme renders the code inverted — which most phone
    // scanners will not read.
    let start = "\u{1B}[30;47m", end = "\u{1B}[0m"
    // The quiet zone is part of the spec, not decoration: without four modules
    // of margin a scanner cannot find the code's edges.
    let margin = 4
    let blank = String(repeating: " ", count: width + margin * 2)

    func dark(_ x: Int, _ y: Int) -> Bool {
        guard x >= 0, y >= 0, x < width, y < height else { return false }
        return (bitmap.colorAt(x: x, y: y)?.brightnessComponent ?? 1) < 0.5
    }

    print("")
    for _ in 0..<(margin / 2) { print(start + blank + end) }
    var y = 0
    while y < height {
        var line = String(repeating: " ", count: margin)
        for x in 0..<width {
            switch (dark(x, y), dark(x, y + 1)) {
            case (true, true):   line += "\u{2588}"
            case (true, false):  line += "\u{2580}"
            case (false, true):  line += "\u{2584}"
            case (false, false): line += " "
            }
        }
        line += String(repeating: " ", count: margin)
        print(start + line + end)
        y += 2
    }
    for _ in 0..<(margin / 2) { print(start + blank + end) }
    print("")
}

switch CommandLine.arguments.dropFirst().first {
case "ocr":
    guard CommandLine.arguments.count > 2 else { die("usage: omacos-helper ocr <image>") }
    ocr(path: CommandLine.arguments[2])
case "color":
    pickColor()
case "qr":
    guard let text = CommandLine.arguments.dropFirst(2).first, !text.isEmpty else {
        die("usage: omacos-helper qr <text>")
    }
    qrCode(text)
case "fonts":
    fontFamilies()
case "clipboard":
    watchClipboard()
default:
    die("usage: omacos-helper <ocr <image>|color>")
}
