-- Loads the colourscheme for the active omacos theme.
-- Regenerated by `omacos theme set`; safe to delete if you want your own.
local theme = vim.fn.expand("~/.local/state/omacos/current/theme/nvim.lua")
if vim.uv.fs_stat(theme) then
  return dofile(theme)
end
return {}
