# Generated by omacos — delta colours for the active theme.
[delta]
	syntax-theme = {{ bat_theme }}
	minus-style = normal {{ mix background red 22% }}
	minus-emph-style = normal {{ mix background red 45% }}
	plus-style = normal {{ mix background green 18% }}
	plus-emph-style = normal {{ mix background green 40% }}
	line-numbers-minus-style = {{ red }}
	line-numbers-plus-style = {{ green }}
	line-numbers-zero-style = {{ muted }}
	file-style = {{ accent }}
	hunk-header-style = {{ muted }}
