# Generated by omacos — theme-derived shell environment.
# Sourced by ~/.config/zsh/.zshrc via the omacos defaults.
export OMACOS_THEME_MODE="{{ mode }}"
export BAT_THEME="{{ bat_theme }}"
export FZF_DEFAULT_OPTS="\
--color=bg+:{{ selection }},bg:-1,spinner:{{ magenta }},hl:{{ red }} \
--color=fg:{{ foreground }},header:{{ red }},info:{{ yellow }},pointer:{{ magenta }} \
--color=marker:{{ green }},fg+:{{ bright_foreground }},prompt:{{ accent }},hl+:{{ red }} \
--color=border:{{ muted }} \
--border=rounded"
