-- Generated by omacos from the active theme's colors.toml — do not edit.
-- Loaded by ~/.config/nvim/lua/plugins/omacos-theme.lua
return {
  { "{{ nvim_plugin }}", name = "{{ nvim_plugin_name }}", lazy = false, priority = 1000 },
  { "LazyVim/LazyVim", opts = { colorscheme = "{{ nvim_colorscheme }}" } },
}
