# Generated by omacos — SketchyBar colours for the active theme.
# Sourced by sketchybarrc; every item reads from these names.
export BAR_COLOR={{ background_0x }}
export BAR_BORDER_COLOR={{ selection_0x }}
export ITEM_BG_COLOR={{ lighter_background_0x }}
export ACCENT_COLOR={{ accent_0x }}
export LABEL_COLOR={{ foreground_0x }}
export ICON_COLOR={{ foreground_0x }}
export DIM_COLOR={{ dark_foreground_0x }}
export HIGHLIGHT_COLOR={{ bright_foreground_0x }}
export RED={{ red_0x }}
export GREEN={{ green_0x }}
export YELLOW={{ yellow_0x }}
export BLUE={{ blue_0x }}
export MAGENTA={{ magenta_0x }}
export CYAN={{ cyan_0x }}
