# Generated by omacos — tmux colours for the active theme.
set -g status-style "bg={{ dark_background }},fg={{ foreground }}"
set -g status-left "#[bg={{ accent }},fg={{ background }},bold] #S #[default] "
set -g status-right "#[fg={{ dark_foreground }}]%H:%M "
set -g window-status-current-style "fg={{ accent }},bold"
set -g window-status-style "fg={{ dark_foreground }}"
set -g pane-border-style "fg={{ selection }}"
set -g pane-active-border-style "fg={{ accent }}"
set -g message-style "bg={{ lighter_background }},fg={{ bright_foreground }}"
